##################################################
# Zscalar
##################################################

FROM python:3.9-bullseye AS zscalar_python_3_9-bullseye
ARG BUILD_D=./docker/dev/build.d
COPY ${BUILD_D}/build.sh /build.d/build.sh
RUN if command -v bash >/dev/null 2>&1; then bash /build.d/build.sh; else sh /build.d/build.sh; fi

##################################################

FROM zscalar_python_3_9-bullseye

RUN mkdir -p /app/panelapp

COPY ./panelapp /app/panelapp
COPY ./setup.py ./setup.cfg ./MANIFEST.in ./VERSION /app/

WORKDIR /app

# Install everything in editable mode, for development
RUN pip install -e .[dev,tests]
RUN pip install pytest-runner

## Prepare installation for development

# Install dev-time dependencies
RUN apt-get update && apt-get install build-essential -y

# Copy the genes file
ADD ./deploy/genes.json.gz /app

# Unbufferend I/O for synchronous logging at dev-time
ENV PYTHONUNBUFFERED 1

# Volume to mount application sources from the host machine
VOLUME ["/app/panelapp"]

WORKDIR /app/panelapp

# Start runserver_plus: useful for development
CMD ["python", "manage.py", "runserver_plus"]
# Note there is a known issue prevending PyCharm debugging if ENTRYPOINT is defined
# https://youtrack.jetbrains.com/issue/PY-32022

# runserver_plus exposes 8000
EXPOSE 8000

