FROM python:3.9-bullseye

COPY README* *build.d /build.d/
RUN bash -c 'for i in $(ls /build.d/*.sh 2>/dev/null | sort) ; do source $i ; done'

RUN mkdir -p /app/panelapp

COPY ./panelapp /app/panelapp
COPY ./setup.py ./setup.cfg ./MANIFEST.in ./VERSION /app/

WORKDIR /app

# Install everything in editable mode, for development
RUN pip install -e .[dev,tests]
RUN pip install pytest-runner

## Prepare installation for development

# Install dev-time dependencies
RUN apt-get update && apt-get install build-essential -y

# Copy the genes file
ADD ./deploy/genes.json.gz /app

# Unbufferend I/O for synchronous logging at dev-time
ENV PYTHONUNBUFFERED 1

# Volume to mount application sources from the host machine
VOLUME ["/app/panelapp"]

WORKDIR /app/panelapp

# Start runserver_plus: useful for development
CMD ["python", "manage.py", "runserver_plus"]
# Note there is a known issue prevending PyCharm debugging if ENTRYPOINT is defined
# https://youtrack.jetbrains.com/issue/PY-32022

# runserver_plus exposes 8000
EXPOSE 8000

