FROM python:3.9-bullseye

COPY README* *build.d /build.d/
RUN bash -c 'for i in $(ls /build.d/*.sh 2>/dev/null | sort) ; do source $i ; done'

RUN apt-get update && apt-get install build-essential -y

# Unbufferend I/O for synchronous logging at dev-time
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /app/panelapp

COPY ./panelapp /app/panelapp
COPY ./setup.py ./setup.cfg ./MANIFEST.in ./VERSION /app/

WORKDIR /app

RUN pip install -e .[dev,tests]
RUN pip install django-debug-toolbar

VOLUME ["/app/panelapp"]

WORKDIR /app/panelapp

# Celery is a script and must run in "shell mode"
# ENTRYPOINT celery worker --app panelapp --task-events --concurrency 1
# CMD ["--loglevel INFO"]
CMD celery worker --app panelapp --task-events --concurrency 1 --loglevel INFO
# Note there is a known issue prevending PyCharm debugging if ENTRYPOINT is defined
# https://youtrack.jetbrains.com/issue/PY-32022
