block-list-secret-scan: []
compact: true
custom-tool-name: Checkov
download-external-modules: false
enable-secret-scan-all-files: true
evaluate-variables: true
framework:
  - all
mask: []
#output:
#  - cli
#  - json
#  - junitxml
#output-file-path: console,checkov.json,checkov.xml
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_7 # Ensure the base image uses a non latest version tag
  - CKV_GITLAB_2 # Ensure all Gitlab groups require two factor authentication
summary-position: top
