version: '3'

services:
  db:
    image: postgres:9.6.9
    environment:
      - POSTGRES_PASSWORD=panelapp
      - POSTGRES_USER=panelapp
      - POSTGRES_DB=panelapp
  nginx:
    image: nginx:1.15.1
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /tmp/panelapp_static:/static
      - /tmp/panelapp_media:/media
    depends_on:
      - web
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=panelapp
  web:
    build: .
    command: gunicorn --workers=4 -b :8000 panelapp.wsgi:application --chdir=/app/panelapp
    volumes:
      - ./panelapp:/app/panelapp
      - /tmp/panelapp_static:/static
      - /tmp/panelapp_media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://panelapp:panelapp@db/panelapp
      - DJANGO_SETTINGS_MODULE=panelapp.settings.base
      - DJANGO_LOG_LEVEL=DEBUG
      - HEALTH_ACCESS_TOKEN_LOCATION=/app/health_token
      - CELERY_BROKER_URL=amqp://rabbitmq/panelapp
      - ALLOWED_HOSTS=localhost;web
      - STATIC_ROOT=/static
      - MEDIA_ROOT=/media
  celery_worker:
    build: .
    command: bash -c "cd /app/panelapp; celery -A panelapp worker -E -l info"
    volumes:
      - ./panelapp:/app/panelapp
      - /tmp/panelapp_static:/static
      - /tmp/panelapp_media:/media
    depends_on:
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://panelapp:panelapp@db/panelapp
      - DJANGO_SETTINGS_MODULE=panelapp.settings.base
      - DJANGO_LOG_LEVEL=DEBUG
      - HEALTH_ACCESS_TOKEN_LOCATION=/app/health_token
      - CELERY_BROKER_URL=amqp://rabbitmq/panelapp
      - ALLOWED_HOSTS=localhost;web
      - STATIC_ROOT=/static
      - MEDIA_ROOT=/media