workflow:
  name: '$WORKFLOW_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    # building and merging
    - if: $deploy_name == "dev" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null
      variables:
        infra_version: $infra_version_new
        AWS_ACCOUNT_ID: "577192787797"
        TEST: "yes"
        WORKFLOW_NAME: ''  # use default
    - if: $deploy_name == "dev" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG
      variables:
        infra_version: $infra_version_new
        AWS_ACCOUNT_ID: "577192787797"
        version: $CI_COMMIT_TAG
        WORKFLOW_NAME: ''  # use default
    # deployment
    - if: $deploy_name == "dev" && $CI_PIPELINE_SOURCE == "web"
      variables:
        infra_version: $infra_version_new
        AWS_ACCOUNT_ID: "577192787797"
    - if: $deploy_name == "dev_old" && $CI_PIPELINE_SOURCE == "web"
      variables:
        account_group: old
        env_name: test
        infra_version: $infra_version_old
        DOCKER_TERRAFORM: $DOCKER_TERRAFORM_OLD
        deploy_runner: "TF_panelapp_test"
        AWS_ACCOUNT_ID: "234335217838"
    - if: $deploy_name == "test" && $CI_PIPELINE_SOURCE == "web"
      variables:
        infra_version: $infra_version_new
        AWS_ACCOUNT_ID: "455662437776"
    - if: $deploy_name == "test_old" && $CI_PIPELINE_SOURCE == "web"
      variables:
        account_group: old
        env_name: stage
        infra_version: $infra_version_old
        DOCKER_TERRAFORM: $DOCKER_TERRAFORM_OLD
        deploy_runner: "TF_panelapp_stage"
        AWS_ACCOUNT_ID: "041401049401"
    # E2E, UAT, and Prod deployments must be triggered manually and from a protected branch
    - if: $deploy_name == "e2e" && $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        infra_version: $infra_version_new
        AWS_ACCOUNT_ID: "875605549679"
    - if: $deploy_name == "uat" && $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        infra_version: $infra_version_new
        AWS_ACCOUNT_ID: "400119055163"
    - if: $deploy_name == "uat_old" && $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        account_group: old
        env_name: uat
        infra_version: $infra_version_old
        DOCKER_TERRAFORM: $DOCKER_TERRAFORM_OLD
        deploy_runner: "TF_panelapp_uat"
        AWS_ACCOUNT_ID: "240121085827"
    - if: $deploy_name == "prod" && $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        infra_version: $infra_version_new
        AWS_ACCOUNT_ID: "876663091628"
    - if: $deploy_name == "prod_old" && $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        account_group: old
        env_name: prod
        infra_version: $infra_version_old
        DOCKER_TERRAFORM: $DOCKER_TERRAFORM_OLD
        deploy_runner: "TF_panelapp_prod"
        AWS_ACCOUNT_ID: "202392872565"
