variables:
  WORKFLOW_NAME: "" # use default

workflow:
  name: "$WORKFLOW_NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG
      variables:
        WORKFLOW_NAME: "Building app: $IMAGE_TAG"
        IMAGE_TAG: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
