# Generated by Django 2.2.28 on 2025-11-18 03:08

from django.db import migrations


def create_training_group(apps, schema_editor):
    """Create the Training group for filtering activity by training users"""
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Training')


def remove_training_group(apps, schema_editor):
    """Remove the Training group"""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Training').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20180725_1029'),
    ]

    operations = [
        migrations.RunPython(create_training_group, remove_training_group),
    ]
