# Generated by Django 2.1.10 on 2019-09-05 16:41

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("panels", "0073_auto_20190710_0811"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsnapshot",
            name="signed_off_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
