# Generated by Django 2.1.10 on 2019-12-06 10:41

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("panels", "0075_genepanelentrysnapshot_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="genepanel",
            name="signed_off",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="panels.HistoricalSnapshot",
            ),
        ),
        migrations.AlterField(
            model_name="trackrecord",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("NewSource", "Added New Source"),
                    ("RemovedSource", "Removed Source"),
                    ("ChangedGeneName", "Changed Gene Name"),
                    ("SetPhenotypes", "Set Phenotypes"),
                    ("SetModelofInheritance", "Set Mode of Inheritance"),
                    ("ClearSources", "Clear Sources"),
                    ("SetModeofPathogenicity", "Set mode of pathogenicity"),
                    (
                        "GeneClassifiedbyGenomicsEnglandCurator",
                        "Gene classified by Genomics England curator",
                    ),
                    (
                        "EntityClassifiedbyGenomicsEnglandCurator",
                        "Entity classified by Genomics England curator",
                    ),
                    ("SetModeofInheritance", "Set mode of inheritance"),
                    ("SetPenetrance", "Set penetrance"),
                    ("SetPublications", "Set publications"),
                    ("SetTranscript", "Set transcript"),
                    ("ApprovedGene", "Approved Gene"),
                    ("ApprovedEntity", "Approved Entity"),
                    ("GelStatusUpdate", "Status Update"),
                    ("UploadGeneInformation", "Upload gene information"),
                    ("RemovedTag", "Removed Tag"),
                    ("AddedTag", "Added Tag"),
                    ("ChangedName", "Changed Name"),
                    ("ChangedSTRName", "Changed STR Name"),
                    ("ChangedChromosome", "Changed Chromosome"),
                    ("ChangedPosition37", "Changed GRCh37"),
                    ("ChangedPosition38", "Changed GRCh38"),
                    ("ChangedNormalRepeats", "Changed Normal Number of Repeats"),
                    (
                        "ChangedPathogenicRepeats",
                        "Changed Pathogenic Number of Repeats",
                    ),
                    ("RemovedGene", "Removed Gene from the STR"),
                    ("ChangedRepeatedSequence", "Changed Repeated Sequence"),
                    ("ChangedEffectTypes", "Changed Effect Types"),
                    ("ChangedVariantType", "Changed Variant Types"),
                    (
                        "ChangedHaploinsufficiencyScore",
                        "Changed Haploinsufficiency Score",
                    ),
                    (
                        "ChangedTriplosensitivityScore",
                        "Changed Triplosensitivity Score",
                    ),
                    (
                        "ChangedRequiredOverlapPercentage",
                        "Changed Required Overlap Percentage",
                    ),
                ],
                max_length=1024,
            ),
        ),
    ]
