# Generated by Django 2.1.10 on 2025-12-01 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("panels", "0076_auto_20191206_1041"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteratureAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="Report directory name, e.g. 'report_2025-01-15'",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "skipped_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required reason for skipping (free text)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current or last assignee (preserved when skipped)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="literature_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="literature_assignments",
                        to="panels.Gene",
                    ),
                ),
                (
                    "skipped_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who marked this as skipped",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skipped_literature_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="literatureassignment",
            index=models.Index(fields=["report_id"], name="lit_assign_report_idx"),
        ),
        migrations.AddIndex(
            model_name="literatureassignment",
            index=models.Index(fields=["assigned_to"], name="lit_assign_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="literatureassignment",
            unique_together={("report_id", "gene")},
        ),
    ]
