# Generated by Django 3.2.22 on 2023-11-30 13:11

from django.db import migrations
from django.db.models import Count

from panels.models.genepanelsnapshot import fix_super_panel_entities


def upgrade(apps, schema_editor):
    fix_super_panel_entities(apps)


class Migration(migrations.Migration):
    dependencies = [
        ("panels", "0077_evaluation_original_panel"),
    ]

    operations = [migrations.RunPython(upgrade)]
