# Generated by Django 2.1.10 on 2025-12-01 11:34

from django.db import migrations


def create_curators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Curators")


def remove_curators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Curators").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("panels", "0077_literatureassignment"),
    ]

    operations = [
        migrations.RunPython(create_curators_group, remove_curators_group),
    ]
