# Generated by Django 4.2.11 on 2024-04-16 12:15

import django.core.serializers.json
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("panels", "0078_super_panel_entities_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="extra_data",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="clinically_relevant",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Interruptions in the repeated sequence are reported as part of standard diagnostic practise",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gene",
            name="ensembl_genes",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="genepanelentrysnapshot",
            name="gene",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="genepanelsnapshot",
            name="stats",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalsnapshot",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="region",
            name="gene",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="str",
            name="gene",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
