# Generated by Django 2.1.10 on 2026-02-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0078_curators_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='hgnc_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
